<?php

namespace CrudBundle\Repository;

/**
 * chouaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chouaRepository extends \Doctrine\ORM\EntityRepository
{
}
