<?php

namespace CrudBundle\Repository;

/**
 * entiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entiRepository extends \Doctrine\ORM\EntityRepository
{
}
