<?php

namespace CrudBundle\Repository;

/**
 * enti111Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enti111Repository extends \Doctrine\ORM\EntityRepository
{
}
