<?php

namespace CrudBundle\Repository;

/**
 * Test4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Test4Repository extends \Doctrine\ORM\EntityRepository
{
}
